### ISSUE TITLE
`extendSchema` Schema definition lacks type instead of any

### ISSUE THREAD

**Issue by MohRaouf** [Josuto/monguito#163]
**Is your feature request related to a problem? Please describe.**
When using `extendSchema` utility function to define the schema definition I can't validate the definition object due to the definition `any` type

**Describe the solution you'd like**
Keep up the great work and support the generic schema definition defined on `extendSchema` so that it assist developers when defining the definition

**Describe alternatives you've considered**
I tried desperately to define a standard Mongoose schema with Types and pass this schema to the `extendSchema` definition argument but it didn't work, it can be an alternative to accepting the standard mongoose schema definition

**Additional context**
Thank you for this great add to the community

**Comment by Josuto** [comment]
Hi @MohRaouf! 

First of all, many thanks for participating in this project! `extendSchema` could definitely have some type definition useful for `monguito` consumers, indeed. I'll work on a solution during this winter break. 

In the meantime, could you please provide an example just to ensure that such a solution supports it?

Many thanks, and also thanks very much for using `monguito`! :-D

**Comment by MohRaouf** [comment]
Thank you @Josuto for your reply 
Here is an example of how it would be helpful to pass Mongoose schema to the `extendSchema` definition 
The following code is not working it's just for explanation.

I don't use the Polymorphic pattern so it's just one default schema.
`BranchMongoSchema` is a standard Mongoose schema with the suggestion feature I'm looking for.

```
export class Branch extends AuditableClass implements Entity {
	readonly id?: string;
	ar: BranchTransFields;
	en: BranchTransFields;
	isPublished: boolean;

	constructor(branch: BranchType) {
		super(branch);
		this.id = branch.id;
		this.ar = branch.ar;
		this.en = branch.en;
		this.isPublished = branch.isPublished;
	}
}

const branchTransFieldsSchema = {
	name: { type: String, required: true, unique: true, index: true },
};

// Define the Mongoose schema
const BranchMongoSchema = new Schema<Branch>({
	ar: { required: true, type: branchTransFieldsSchema, _id: false },
	en: { required: true, type: branchTransFieldsSchema, _id: false },
	isPublished: {
		type: Boolean,
		default: false,
		required: true,
		index: true,
	},
});

// Create and export the model
// const BranchModel = model<Branch>('branch', BranchMongoSchema);

export const BranchSchema = extendSchema(BaseSchema, BranchMongoSchema);
```

Thank you again for such a masterpiece of work 👏

**Comment by Josuto** [comment]
Hi again @MohRaouf!

I understand that your code is for explanatory purposes. However, I'm in the need to make a couple of observations for clarification and understandability purposes:

- First and foremost, `extendSchema` is invoked passing two schemas (i.e., `BaseSchema` and `BranchMongoSchema`). However, the signature of this function is `extendSchema(Schema, SchemaDefinition, SchemaOptions?)`. In other other words, you should invoke it as follows: `extendSchema(BaseSchema, BranchMongoSchema.obj)`.
- Also, the instantiation of `BranchMongoSchema` can be improved: `ar` and `en` `type`s are expected to be instances of Mongoose `Schema`. Besides, `_id: false ` is meant to be a schema option. Thus, this piece of the code could be written as follows:

```
type BranchTransFields = {
  name: string;
};

const BranchTransFieldsSchema = new Schema<BranchTransFields>(
  {
    name: { type: String, required: true, unique: true, index: true },
  },
  { _id: false },
);

// Define the Mongoose schema
const BranchMongoSchema: Schema<Branch> = new Schema<Branch>({
  ar: { type: BranchTransFieldsSchema, required: true },
  en: { type: BranchTransFieldsSchema, required: true },
  isPublished: {
    type: Boolean,
    default: false,
    required: true,
    index: true,
  },
});

export const BranchSchema: Schema<Branch> = extendSchema<{}, Branch>(
  BaseSchema,
  BranchMongoSchema.obj,
);
```

Finally, I'm about to release a new version of `monguito` that specifies the following `extendSchema` type definition:

```
export function extendSchema<T = {}, S = {}>(
  schema: Schema<T>,
  definition: SchemaDefinition<S>,
  options?: SchemaOptions,
): Schema<T & S>
```

This type definition complies with any use case for extending any schema with any arbitrary schema definition and options. I believe that it would also help you 😊. 

Please let me know if I have misunderstood you in any way

**Comment by MohRaouf** [comment]
@Josuto 
I'm satisfied with your reply, thank you again, 
I can't wait to test the new version 👏
