### ISSUE TITLE
The 'monguito' library may need to update its package.json or typings. ts(7016)

### ISSUE THREAD

**Issue by filiphsps** [Josuto/monguito#201]
```There are types at '/node_modules/monguito/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'monguito' library may need to update its package.json or typings. ts(7016)```

**Comment by Josuto** [comment]
Hi @filiphsps. Thanks for your feedback. 

Could you please provide a bit of context such as how to reproduce this issue? I am using `monguito` in a private project and not getting this TS error message myself.

Many thanks.

**Comment by filiphsps** [comment]
Hi, sorry; I left this issue hastily here to remind me to investigate later this week if it's our env or if there's some larger underlying issue.

My guess would be that it's related to our ts setup (somewhat bleeding edge), more specifically ```["module": "ESNext", "moduleDetection": "force", "moduleResolution": "Bundler"]``` but I have yet to investigate 🤠

**Comment by Josuto** [comment]
Hey @filiphsps, many thanks for your feedback! 

I updated the TS config options of the NestJS sample application included in this repository and confirmed that your issue is indeed legitimate. I am currently working on a solution, but may need a bit of time to release it (hopefully by the end of today). Will keep you posted! 👾

**Comment by filiphsps** [comment]
Howdy @Josuto!

I'm not using NestJS, been working on a sub-package for a next.js project as prisma/postgresql was just.. ugh. and monguito looks like a neat way to deal with some painpoints for that, so I'm experimenting with it. Since the company we were building is probably getting closed down I might end up open sourcing everything, I'll let you know if that's the case and if monguito ends up getting used.
